### ISSUE TITLE
after a certain amount of charts, upon completion of importing them, that application hangs, and hangs on startup

### ISSUE THREAD

**Issue by nootskoot** [m8nscape/lunaticvibes#60]
as title says, after a certain point in the import process, following the completion for importing said songs, the application completely hangs, rendering unusable

for me my song count is 135k
and the terminal logger is just filled with this,

i have tried reinstalling the program, as well as removing databases in relation to it altogether.
![image](https://github.com/m8nscape/lunaticvibes/assets/61766076/0d74b5c8-e90c-4bbc-a039-0a6c2491aa5a)

it can be reproduced by simply importing a large number of charts, for me this is 135k, however it may be lower

**Comment by nootskoot** [comment]
not songs, but foreign or unknown characters,

**Comment by Vad1mCSO2** [comment]
So just, not planned...
